export const LSP_USER_ID = 'lsp-user-id'
export const LSP_ACCOUNT_ID = 'lsp-account-id'
export const LSP_AUTH_TOKEN = 'lsp-auth-token'
export const LSP_USERNAME = 'lsp-username'
export const API_BASE_URL = 'https://apisituk.ourdailycode.com/graphql'